services:
  mysql:
    image: mysql:8.0.30
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wage
      MYSQL_DATABASE: wage
      MYSQL_USER: wage
      MYSQL_PASSWORD: wage
    ports:
      - "3306:3306"
    networks:
      - springboot-network
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
      - springboot-network
    ports:
      - "2181:2181"
  kafka-server:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ADVERTISED_HOST_NAME: kafka-server
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:9092
    networks:
      - springboot-network
    depends_on:
      - zookeeper
  consumer:
    build:
      context: .
      dockerfile: wage-consumer.Dockerfile
    depends_on:
      - mysql
      - kafka-server
    networks:
      - springboot-network
#   Uncomment to use custom config location
#    volumes:
#      - /Users/ataran/Documents/wage-configs/consumer:/config
    ports:
      - "8081:8080"
    expose:
      - "8081"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  producer:
    build:
      context: .
      dockerfile: wage-producer.Dockerfile
    depends_on:
      - kafka-server
    networks:
      - springboot-network
#   Uncomment to use custom config location
#    volumes:
#      - /Users/ataran/Documents/wage-configs/producer:/config
    ports:
      - "8082:8080"
    expose:
      - "8082"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  springboot-network:
    driver: bridge
