messaging:
  user-wage-topic: user-wage-topic
  concurrency: 5
  consumer-group-name: wage-consumer-group
  poll-timeout: 3000
wage:
  tax-rate: 0.1
spring:
  kafka:
    properties:
      bootstrap:
        servers: PLAINTEXT://kafka-server:9092
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://mysql:3306/wage
    username: wage
    password: wage
  liquibase:
    enabled: true