messaging:
  user-wage-topic: user-wage-topic
  concurrency: 1
  consumer-group-name: wage-consumer-group
  poll-timeout: 3000
wage:
  tax-rate: 0.1
spring:
  kafka:
    properties:
      bootstrap:
        servers: PLAINTEXT://kafka-server:9092
  datasource:
    url: jdbc:mysql://mysql:3306/wage
    username: wage
    password: wage
  liquibase:
    enabled: true
listener:
  concurrency: 3
  poll-timeout: 3000
