messaging:
  user-wage-topic: user-wage-topic
  partitions: 10

spring:
  kafka:
    properties:
      bootstrap:
        servers: PLAINTEXT://kafka-server:9092
  mvc:
    path-match:
      matching-strategy: ant_path_matcher